<?php
/**
 * Button | startapp_button
 *
 * @author 8guild
 */

return array(
	'name'     => __( 'Button', 'startapp' ),
	'category' => __( 'StartApp', 'startapp' ),
	'icon'     => 'icon-wpb-ui-button',
	'params'   => startapp_vc_map_params( array(
		array(
			'param_name'  => 'text',
			'type'        => 'textfield',
			'weight'      => 10,
			'heading'     => __( 'Text', 'startapp' ),
			'admin_label' => true,
		),
		array(
			'param_name' => 'link',
			'type'       => 'vc_link',
			'weight'     => 10,
		),
		array(
			'param_name'       => 'type',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Type', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'value'            => array(
				__( 'Solid', 'startapp' )       => 'solid',
				__( 'Ghost', 'startapp' )       => 'ghost',
				__( '3D', 'startapp' )          => '3d',
				__( 'Transparent', 'startapp' ) => 'transparent',
				__( 'Link', 'startapp' )        => 'link',
			),
		),
		array(
			'param_name'       => 'shape',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Shape', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'value'            => array(
				__( 'Rounded', 'startapp' ) => 'rounded',
				__( 'Square', 'startapp' )  => 'square',
				__( 'Pill', 'startapp' )    => 'pill',
			),
		),
		array(
			'param_name'         => 'color',
			'type'               => 'dropdown',
			'weight'             => 10,
			'heading'            => __( 'Color', 'startapp' ),
			'param_holder_class' => 'guild-colored',
			'edit_field_class'   => 'vc_col-sm-4',
			'std'                => 'default',
			'value'              => array(
				__( 'Default', 'startapp' ) => 'default',
				__( 'Primary', 'startapp' ) => 'primary',
				__( 'Success', 'startapp' ) => 'success',
				__( 'Info', 'startapp' )    => 'info',
				__( 'Warning', 'startapp' ) => 'warning',
				__( 'Danger', 'startapp' )  => 'danger',
				__( 'Light', 'startapp' )   => 'light',
				__( 'Custom', 'startapp' )  => 'custom',
			),
		),
		array(
			'param_name'       => 'color_custom',
			'type'             => 'colorpicker',
			'weight'           => 10,
			'heading'          => __( 'Custom Color', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-12',
			'dependency'       => array( 'element' => 'color', 'value' => 'custom' ),
		),
		array(
			'param_name'       => 'size',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Size', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'nl',
			'value'            => array(
				__( 'Large', 'startapp' )       => 'lg',
				__( 'Normal', 'startapp' )      => 'nl',
				__( 'Small', 'startapp' )       => 'sm',
				__( 'Extra Small', 'startapp' ) => 'xs',
			),
		),
		array(
			'param_name'       => 'is_full',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Make button full-width?', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'no',
			'value'            => array(
				__( 'No', 'startapp' )  => 'no',
				__( 'Yes', 'startapp' ) => 'yes',
			),
		),
		array(
			'param_name'       => 'alignment',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Alignment', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'inline',
			'value'            => array(
				__( 'Inline', 'startapp' ) => 'inline',
				__( 'Left', 'startapp' )   => 'left',
				__( 'Center', 'startapp' ) => 'center',
				__( 'Right', 'startapp' )  => 'right',
			),
		),
		array(
			'param_name'       => 'is_waves',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Waves Effect', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'disable',
			'value'            => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
		array(
			'param_name'       => 'waves_skin',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Waves Color', 'startapp' ),
			'dependency'       => array( 'element' => 'is_waves', 'value' => 'enable' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'light',
			'value'            => array(
				__( 'Dark', 'startapp' )  => 'dark',
				__( 'Light', 'startapp' ) => 'light',
			),
		),
		array(
			'param_name'       => 'is_icon',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Icon', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'disable',
			'value'            => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
		array(
			'param_name'       => 'icon_library',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Icon Library', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-6',
			'dependency'       => array( 'element' => 'is_icon', 'value' => 'enable' ),
			'std'              => 'none',
			'value'            => array(
				__( 'Font Awesome', 'startapp' ) => 'fontawesome',
				__( 'Material', 'startapp' )     => 'material',
				__( 'Custom', 'startapp' )       => 'custom',
			),
		),
		array(
			'param_name'       => 'icon_position',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Icon Position', 'startapp' ),
			'edit_field_class' => 'vc_col-sm-6',
			'dependency'       => array( 'element' => 'is_icon', 'value' => 'enable' ),
			'std'              => 'left',
			'value'            => array(
				__( 'Left', 'startapp' )  => 'left',
				__( 'Right', 'startapp' ) => 'right',
			),
		),
		array(
			'param_name' => 'icon_fontawesome',
			'type'       => 'iconpicker',
			'weight'     => 10,
			'heading'    => __( 'Icon', 'startapp' ),
			'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
			'dependency' => array( 'element' => 'icon_library', 'value' => 'fontawesome' ),
		),
		array(
			'param_name' => 'icon_material',
			'type'       => 'iconpicker',
			'weight'     => 10,
			'heading'    => __( 'Icon', 'startapp' ),
			'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
			'dependency' => array( 'element' => 'icon_library', 'value' => 'material' ),
		),
		array(
			'param_name'  => 'icon_custom',
			'type'        => 'textfield',
			'weight'      => 10,
			'heading'     => __( 'Icon', 'startapp' ),
			'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
				'ol' => true,
				'li' => true,
			) ),
			'dependency'  => array( 'element' => 'icon_library', 'value' => 'custom' ),
		),
	), 'startapp_button' ),
);
