<?php
/**
 * Steps | startapp_steps
 *
 * @author 8guild
 */

return array(
	'name'     => __( 'Steps', 'startapp' ),
	'category' => __( 'StartApp', 'startapp' ),
	'icon'     => '',
	'params'   => startapp_vc_map_params( array_merge(
		array(
			array(
				'param_name' => 'skin',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Skin', 'startapp' ),
				'std'        => 'dark',
				'value'      => array(
					__( 'Dark', 'startapp' )  => 'dark',
					__( 'Light', 'startapp' ) => 'light',
				),
			),
		),
		array(
			array(
				'param_name' => 'first_label',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Label', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'value'      => __( 'Step 1', 'startapp' ),
			),
			array(
				'param_name' => 'first_type',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon Type', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'std'        => 'image',
				'value'      => array(
					__( 'Image', 'startapp' )     => 'image',
					__( 'Font Icon', 'startapp' ) => 'icon',
				),
			),
			array(
				'param_name'       => 'first_icon_library',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon library', 'startapp' ),
				'group'            => __( 'Step 1', 'startapp' ),
				'dependency'       => array( 'element' => 'first_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'none',
				'value'            => array(
					__( 'Font Awesome', 'startapp' ) => 'fontawesome',
					__( 'Material', 'startapp' )     => 'material',
					__( 'Custom', 'startapp' )       => 'custom',
				),
			),
			array(
				'param_name'       => 'first_icon_color',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Color', 'startapp' ),
				'group'            => __( 'Step 1', 'startapp' ),
				'dependency'       => array( 'element' => 'first_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'default',
				'value'            => array(
					__( 'Default', 'startapp' ) => 'default',
					__( 'Primary', 'startapp' ) => 'primary',
					__( 'Success', 'startapp' ) => 'success',
					__( 'Info', 'startapp' )    => 'info',
					__( 'Warning', 'startapp' ) => 'warning',
					__( 'Danger', 'startapp' )  => 'danger',
					__( 'Muted', 'startapp' )   => 'muted',
					__( 'Gray', 'startapp' )    => 'gray',
					__( 'Light', 'startapp' )   => 'light',
					__( 'Custom', 'startapp' )  => 'custom',
				),
			),
			array(
				'param_name' => 'first_icon_color_custom',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Custom Icon Color', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'dependency' => array( 'element' => 'first_icon_color', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'first_icon_fontawesome',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'first_icon_library', 'value' => 'fontawesome' ),
			),
			array(
				'param_name' => 'first_icon_material',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'first_icon_library', 'value' => 'material' ),
			),
			array(
				'param_name'  => 'first_icon_custom',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Icon', 'startapp' ),
				'group'       => __( 'Step 1', 'startapp' ),
				'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
					'ol' => true,
					'li' => true,
				) ),
				'dependency'  => array( 'element' => 'first_icon_library', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'first_image',
				'type'       => 'attach_image',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'dependency' => array( 'element' => 'first_type', 'value' => 'image' ),
			),
			array(
				'param_name' => 'first_title',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Title', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
			),
			array(
				'param_name' => 'first_description',
				'type'       => 'textarea',
				'weight'     => 10,
				'heading'    => __( 'Description', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
			),
			array(
				'param_name' => 'first_hover',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Hover Background', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'dependency' => array( 'element' => 'skin', 'value_not_equal_to' => 'light' ),
				'value'      => '#000000',
			),
			array(
				'param_name' => 'first_is_button',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Add button?', 'startapp' ),
				'group'      => __( 'Step 1', 'startapp' ),
				'std'        => 'no',
				'value'      => array(
					__( 'No', 'startapp' )  => 'no',
					__( 'Yes', 'startapp' ) => 'yes',
				),
			),
		),
		(array) vc_map_integrate_shortcode( 'startapp_button', 'first_btn_', __( 'Step 1', 'startapp' ),
			array( 'exclude_regex' => '/(animation|icon)/' ),
			array( 'element' => 'first_is_button', 'value' => 'yes' )
		),
		array(
			array(
				'param_name' => 'second_label',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Label', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'value'      => __( 'Step 2', 'startapp' ),
			),
			array(
				'param_name' => 'second_type',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon Type', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'std'        => 'image',
				'value'      => array(
					__( 'Image', 'startapp' )     => 'image',
					__( 'Font Icon', 'startapp' ) => 'icon',
				),
			),
			array(
				'param_name'       => 'second_icon_library',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon library', 'startapp' ),
				'group'            => __( 'Step 2', 'startapp' ),
				'dependency'       => array( 'element' => 'second_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'none',
				'value'            => array(
					__( 'Font Awesome', 'startapp' ) => 'fontawesome',
					__( 'Material', 'startapp' )     => 'material',
					__( 'Custom', 'startapp' )       => 'custom',
				),
			),
			array(
				'param_name'       => 'second_icon_color',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Color', 'startapp' ),
				'group'            => __( 'Step 2', 'startapp' ),
				'dependency'       => array( 'element' => 'second_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'default',
				'value'            => array(
					__( 'Default', 'startapp' ) => 'default',
					__( 'Primary', 'startapp' ) => 'primary',
					__( 'Success', 'startapp' ) => 'success',
					__( 'Info', 'startapp' )    => 'info',
					__( 'Warning', 'startapp' ) => 'warning',
					__( 'Danger', 'startapp' )  => 'danger',
					__( 'Muted', 'startapp' )   => 'muted',
					__( 'Gray', 'startapp' )    => 'gray',
					__( 'Light', 'startapp' )   => 'light',
					__( 'Custom', 'startapp' )  => 'custom',
				),
			),
			array(
				'param_name' => 'second_icon_color_custom',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Custom Icon Color', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'dependency' => array( 'element' => 'second_icon_color', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'second_icon_fontawesome',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'second_icon_library', 'value' => 'fontawesome' ),
			),
			array(
				'param_name' => 'second_icon_material',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'second_icon_library', 'value' => 'material' ),
			),
			array(
				'param_name'  => 'second_icon_custom',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Icon', 'startapp' ),
				'group'       => __( 'Step 2', 'startapp' ),
				'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
					'ol' => true,
					'li' => true,
				) ),
				'dependency'  => array( 'element' => 'second_icon_library', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'second_image',
				'type'       => 'attach_image',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'dependency' => array( 'element' => 'second_type', 'value' => 'image' ),
			),
			array(
				'param_name' => 'second_title',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Title', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
			),
			array(
				'param_name' => 'second_description',
				'type'       => 'textarea',
				'weight'     => 10,
				'heading'    => __( 'Description', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
			),
			array(
				'param_name' => 'second_hover',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Hover Background', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'dependency' => array( 'element' => 'skin', 'value_not_equal_to' => 'light' ),
				'value'      => '#000000',
			),
			array(
				'param_name' => 'second_is_button',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Add button?', 'startapp' ),
				'group'      => __( 'Step 2', 'startapp' ),
				'std'        => 'no',
				'value'      => array(
					__( 'No', 'startapp' )  => 'no',
					__( 'Yes', 'startapp' ) => 'yes',
				),
			),
		),
		(array) vc_map_integrate_shortcode( 'startapp_button', 'second_btn_', __( 'Step 2', 'startapp' ),
			array( 'exclude_regex' => '/(animation|icon)/' ),
			array( 'element' => 'second_is_button', 'value' => 'yes' )
		),
		array(
			array(
				'param_name' => 'third_label',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Label', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'value'      => __( 'Step 3', 'startapp' ),
			),
			array(
				'param_name' => 'third_type',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon Type', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'std'        => 'image',
				'value'      => array(
					__( 'Image', 'startapp' )     => 'image',
					__( 'Font Icon', 'startapp' ) => 'icon',
				),
			),
			array(
				'param_name'       => 'third_icon_library',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon library', 'startapp' ),
				'group'            => __( 'Step 3', 'startapp' ),
				'dependency'       => array( 'element' => 'third_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'none',
				'value'            => array(
					__( 'Font Awesome', 'startapp' ) => 'fontawesome',
					__( 'Material', 'startapp' )     => 'material',
					__( 'Custom', 'startapp' )       => 'custom',
				),
			),
			array(
				'param_name'       => 'third_icon_color',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Color', 'startapp' ),
				'group'            => __( 'Step 3', 'startapp' ),
				'dependency'       => array( 'element' => 'third_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'default',
				'value'            => array(
					__( 'Default', 'startapp' ) => 'default',
					__( 'Primary', 'startapp' ) => 'primary',
					__( 'Success', 'startapp' ) => 'success',
					__( 'Info', 'startapp' )    => 'info',
					__( 'Warning', 'startapp' ) => 'warning',
					__( 'Danger', 'startapp' )  => 'danger',
					__( 'Muted', 'startapp' )   => 'muted',
					__( 'Gray', 'startapp' )    => 'gray',
					__( 'Light', 'startapp' )   => 'light',
					__( 'Custom', 'startapp' )  => 'custom',
				),
			),
			array(
				'param_name' => 'third_icon_color_custom',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Custom Icon Color', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'dependency' => array( 'element' => 'third_icon_color', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'third_icon_fontawesome',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'third_icon_library', 'value' => 'fontawesome' ),
			),
			array(
				'param_name' => 'third_icon_material',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'third_icon_library', 'value' => 'material' ),
			),
			array(
				'param_name'  => 'third_icon_custom',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Icon', 'startapp' ),
				'group'       => __( 'Step 3', 'startapp' ),
				'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
					'ol' => true,
					'li' => true,
				) ),
				'dependency'  => array( 'element' => 'third_icon_library', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'third_image',
				'type'       => 'attach_image',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'dependency' => array( 'element' => 'third_type', 'value' => 'image' ),
			),
			array(
				'param_name' => 'third_title',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Title', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
			),
			array(
				'param_name' => 'third_description',
				'type'       => 'textarea',
				'weight'     => 10,
				'heading'    => __( 'Description', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
			),
			array(
				'param_name' => 'third_hover',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Hover Background', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'dependency' => array( 'element' => 'skin', 'value_not_equal_to' => 'light' ),
				'value'      => '#000000',
			),
			array(
				'param_name' => 'third_is_button',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Add button?', 'startapp' ),
				'group'      => __( 'Step 3', 'startapp' ),
				'std'        => 'no',
				'value'      => array(
					__( 'No', 'startapp' )  => 'no',
					__( 'Yes', 'startapp' ) => 'yes',
				),
			),
		),
		(array) vc_map_integrate_shortcode( 'startapp_button', 'third_btn_', __( 'Step 3', 'startapp' ),
			array( 'exclude_regex' => '/(animation|icon)/' ),
			array( 'element' => 'third_is_button', 'value' => 'yes' )
		),
		array(
			array(
				'param_name' => 'fourth_label',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Label', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'value'      => __( 'Step 4', 'startapp' ),
			),
			array(
				'param_name' => 'fourth_type',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon Type', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'std'        => 'image',
				'value'      => array(
					__( 'Image', 'startapp' )     => 'image',
					__( 'Font Icon', 'startapp' ) => 'icon',
				),
			),
			array(
				'param_name'       => 'fourth_icon_library',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon library', 'startapp' ),
				'group'            => __( 'Step 4', 'startapp' ),
				'dependency'       => array( 'element' => 'fourth_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'none',
				'value'            => array(
					__( 'Font Awesome', 'startapp' ) => 'fontawesome',
					__( 'Material', 'startapp' )     => 'material',
					__( 'Custom', 'startapp' )       => 'custom',
				),
			),
			array(
				'param_name'       => 'fourth_icon_color',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Color', 'startapp' ),
				'group'            => __( 'Step 4', 'startapp' ),
				'dependency'       => array( 'element' => 'fourth_type', 'value' => 'icon' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'default',
				'value'            => array(
					__( 'Default', 'startapp' ) => 'default',
					__( 'Primary', 'startapp' ) => 'primary',
					__( 'Success', 'startapp' ) => 'success',
					__( 'Info', 'startapp' )    => 'info',
					__( 'Warning', 'startapp' ) => 'warning',
					__( 'Danger', 'startapp' )  => 'danger',
					__( 'Muted', 'startapp' )   => 'muted',
					__( 'Gray', 'startapp' )    => 'gray',
					__( 'Light', 'startapp' )   => 'light',
					__( 'Custom', 'startapp' )  => 'custom',
				),
			),
			array(
				'param_name' => 'fourth_icon_color_custom',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Custom Icon Color', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'dependency' => array( 'element' => 'fourth_icon_color', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'fourth_icon_fontawesome',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'fourth_icon_library', 'value' => 'fontawesome' ),
			),
			array(
				'param_name' => 'fourth_icon_material',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'fourth_icon_library', 'value' => 'material' ),
			),
			array(
				'param_name'  => 'fourth_icon_custom',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Icon', 'startapp' ),
				'group'       => __( 'Step 4', 'startapp' ),
				'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
					'ol' => true,
					'li' => true,
				) ),
				'dependency'  => array( 'element' => 'fourth_icon_library', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'fourth_image',
				'type'       => 'attach_image',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'dependency' => array( 'element' => 'fourth_type', 'value' => 'image' ),
			),
			array(
				'param_name' => 'fourth_title',
				'type'       => 'textfield',
				'weight'     => 10,
				'heading'    => __( 'Title', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
			),
			array(
				'param_name' => 'fourth_description',
				'type'       => 'textarea',
				'weight'     => 10,
				'heading'    => __( 'Description', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
			),
			array(
				'param_name' => 'fourth_hover',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Hover Background', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'dependency' => array( 'element' => 'skin', 'value_not_equal_to' => 'light' ),
				'value'      => '#000000',
			),
			array(
				'param_name' => 'fourth_is_button',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Add button?', 'startapp' ),
				'group'      => __( 'Step 4', 'startapp' ),
				'std'        => 'no',
				'value'      => array(
					__( 'No', 'startapp' )  => 'no',
					__( 'Yes', 'startapp' ) => 'yes',
				),
			),
		),
		(array) vc_map_integrate_shortcode( 'startapp_button', 'fourth_btn_', __( 'Step 4', 'startapp' ),
			array( 'exclude_regex' => '/(animation|icon)/' ),
			array( 'element' => 'fourth_is_button', 'value' => 'yes' )
		)
	), 'startapp_steps' ),
);
