<?php
/**
 * Icon Box | startapp_icon_box
 *
 * @author 8guild
 */

return array(
	'name'     => __( 'Icon Box', 'startapp' ),
	'category' => __( 'StartApp', 'startapp' ),
	'icon'     => '',
	'params'   => startapp_vc_map_params( array_merge(
		array(
			array(
				'param_name' => 'layout',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Layout', 'startapp' ),
				'std'        => 'vertical',
				'value'      => array(
					__( 'Vertical', 'startapp' )   => 'vertical',
					__( 'Horizontal', 'startapp' ) => 'horizontal',
				),
			),
			array(
				'param_name'       => 'alignment',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Alignment', 'startapp' ),
				'dependency'       => array( 'element' => 'layout', 'value' => 'vertical' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'left',
				'value'            => array(
					__( 'Left', 'startapp' )   => 'left',
					__( 'Center', 'startapp' ) => 'center',
					__( 'Right', 'startapp' )  => 'right',
				),
			),
			array(
				'param_name'       => 'icon_position',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Position', 'startapp' ),
				'dependency'       => array( 'element' => 'layout', 'value' => 'horizontal' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'left',
				'value'            => array(
					__( 'Left', 'startapp' )  => 'left',
					__( 'Right', 'startapp' ) => 'right',
				),
			),
			array(
				'param_name'       => 'type',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Icon Type', 'startapp' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'image',
				'value'            => array(
					__( 'Image', 'startapp' )     => 'image',
					__( 'Font Icon', 'startapp' ) => 'icon',
				),
			),
			array(
				'param_name' => 'icon_library',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon library', 'startapp' ),
				'dependency' => array( 'element' => 'type', 'value' => 'icon' ),
				'std'        => 'none',
				'value'      => array(
					__( 'Font Awesome', 'startapp' ) => 'fontawesome',
					__( 'Material', 'startapp' )     => 'material',
					__( 'Custom', 'startapp' )       => 'custom',
				),
			),
			array(
				'param_name' => 'icon_fontawesome',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'settings'   => array( 'type' => 'fontawesome', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'icon_library', 'value' => 'fontawesome' ),
			),
			array(
				'param_name' => 'icon_material',
				'type'       => 'iconpicker',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'settings'   => array( 'type' => 'material', 'iconsPerPage' => 500 ),
				'dependency' => array( 'element' => 'icon_library', 'value' => 'material' ),
			),
			array(
				'param_name'  => 'icon_custom',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Icon', 'startapp' ),
				'description' => wp_kses( __( 'Class should be written without leading dot. There are two options to add custom icons: <ol><li>You can link your custom icon CSS file in Theme Options > Advanced</li><li>You can manually enqueue custom icons CSS file in the Child Theme</li></ol>', 'startapp' ), array(
					'ol' => true,
					'li' => true,
				) ),
				'dependency'  => array( 'element' => 'icon_library', 'value' => 'custom' ),
			),
			array(
				'param_name' => 'image',
				'type'       => 'attach_image',
				'weight'     => 10,
				'heading'    => __( 'Icon', 'startapp' ),
				'dependency' => array( 'element' => 'type', 'value' => 'image' ),
			),
			array(
				'param_name' => 'icon_color',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Icon Color', 'startapp' ),
				'dependency' => array( 'element' => 'type', 'value' => 'icon' ),
				'std'        => 'default',
				'value'      => array(
					__( 'Default', 'startapp' ) => 'default',
					__( 'Primary', 'startapp' ) => 'primary',
					__( 'Success', 'startapp' ) => 'success',
					__( 'Info', 'startapp' )    => 'info',
					__( 'Warning', 'startapp' ) => 'warning',
					__( 'Danger', 'startapp' )  => 'danger',
					__( 'Muted', 'startapp' )   => 'muted',
					__( 'Gray', 'startapp' )    => 'gray',
					__( 'Light', 'startapp' )   => 'light',
					__( 'Custom', 'startapp' )  => 'custom',
				),
			),
			array(
				'param_name' => 'icon_color_custom',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Custom Icon Color', 'startapp' ),
				'dependency' => array( 'element' => 'icon_color', 'value' => 'custom' ),
			),
			array(
				'param_name'  => 'title',
				'type'        => 'textfield',
				'weight'      => 10,
				'heading'     => __( 'Title', 'startapp' ),
				'admin_label' => true,
			),
			array(
				'param_name' => 'content',
				'type'       => 'textarea_html',
				'weight'     => 10,
				'heading'    => __( 'Description', 'startapp' ),
			),
			array(
				'param_name' => 'background',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Background Type', 'startapp' ),
				'dependency' => array( 'element' => 'layout', 'value' => 'vertical' ),
				'std'        => 'no',
				'value'      => array(
					__( 'No', 'startapp' )       => 'no',
					__( 'On Hover', 'startapp' ) => 'hover',
					__( 'Static', 'startapp' )   => 'static',
				),
			),
			array(
				'param_name' => 'background_color',
				'type'       => 'colorpicker',
				'weight'     => 10,
				'heading'    => __( 'Background Color', 'startapp' ),
				'dependency' => array( 'element' => 'background', 'value' => array( 'hover', 'static' ) ),
			),
			array(
				'param_name' => 'background_effect',
				'type'       => 'dropdown',
				'weight'     => 10,
				'heading'    => __( 'Hover Effect', 'startapp' ),
				'dependency' => array( 'element' => 'background', 'value' => 'hover' ),
				'std'        => 'fade',
				'value'      => array(
					__( 'Fade', 'startapp' )            => 'fade',
					__( 'From Top', 'startapp' )        => 'from-top',
					__( 'From Bottom', 'startapp' )     => 'from-bottom',
					__( 'From Left', 'startapp' )       => 'from-left',
					__( 'From Right', 'startapp' )      => 'from-right',
					__( 'Scale Up', 'startapp' )        => 'scale-up',
					__( 'Scale Down', 'startapp' )      => 'scale-down',
					__( 'Flip Vertical', 'startapp' )   => 'flip-vertical',
					__( 'Flip Horizontal', 'startapp' ) => 'flip-horizontal',
				),
			),
			array(
				'param_name'       => 'skin',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Skin', 'startapp' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'dark',
				'value'            => array(
					__( 'Dark', 'startapp' )  => 'dark',
					__( 'Light', 'startapp' ) => 'light',
				),
			),
			array(
				'param_name'       => 'is_button',
				'type'             => 'dropdown',
				'weight'           => 10,
				'heading'          => __( 'Add button?', 'startapp' ),
				'edit_field_class' => 'vc_col-sm-6',
				'std'              => 'no',
				'value'            => array(
					__( 'No', 'startapp' )  => 'no',
					__( 'Yes', 'startapp' ) => 'yes',
				),
			),
		),
		(array) vc_map_integrate_shortcode( 'startapp_button', 'button_', __( 'Button', 'startapp' ),
			array( 'exclude_regex' => '/(animation|icon)/' ),
			array( 'element' => 'is_button', 'value' => 'yes' )
		)
	), 'startapp_icon_box' ),
);
