<?php
/**
 * Image Carousel | startapp_image_carousel
 *
 * @author 8guild
 */

return array(
	'name'     => __( 'Image Carousel', 'startapp' ),
	'category' => __( 'StartApp', 'startapp' ),
	'icon'     => 'icon-wpb-images-carousel',
	'params'   => startapp_vc_map_params( array(
		array(
			'param_name' => 'images',
			'type'       => 'attach_images',
			'weight'     => 10,
			'heading'    => __( 'Images', 'startapp' ),
		),
		array(
			'param_name' => 'is_caption',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Captions', 'startapp' ),
			'std'        => 'disable',
			'value'      => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
		array(
			'param_name' => 'is_arrows',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Show Arrows', 'startapp' ),
			'group'      => __( 'Controls', 'startapp' ),
			'std'        => 'show',
			'value'      => array(
				__( 'Show', 'startapp' ) => 'show',
				__( 'Hide', 'startapp' ) => 'hide',
			),
		),
		array(
			'param_name'       => 'arrows_shape',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Arrows Shape', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_arrows', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'rounded',
			'value'            => array(
				__( 'Rounded', 'startapp' ) => 'rounded',
				__( 'Circle', 'startapp' )  => 'circle',
				__( 'Square', 'startapp' )  => 'square',
			),
		),
		array(
			'param_name'       => 'arrows_size',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Arrows Size', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_arrows', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'sm',
			'value'            => array(
				__( 'Small', 'startapp' ) => 'sm',
				__( 'Large', 'startapp' ) => 'lg',
			),
		),
		array(
			'param_name'       => 'arrows_position',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Arrows Position', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_arrows', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'on-sides',
			'value'            => array(
				__( 'On sides', 'startapp' )  => 'on-sides',
				__( 'Top Right', 'startapp' ) => 'top-right',
				__( 'Top Left', 'startapp' )  => 'top-left',
			),
		),
		array(
			'param_name' => 'is_dots',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Show Dots', 'startapp' ),
			'group'      => __( 'Controls', 'startapp' ),
			'std'        => 'show',
			'value'      => array(
				__( 'Show', 'startapp' ) => 'show',
				__( 'Hide', 'startapp' ) => 'hide',
			),
		),
		array(
			'param_name'       => 'dots_skin',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Dots Skin', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_dots', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'dark',
			'value'            => array(
				__( 'Dark', 'startapp' )  => 'dark',
				__( 'Light', 'startapp' ) => 'light',
			),
		),
		array(
			'param_name'       => 'dots_position',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Dots Position', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_dots', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'outside',
			'value'            => array(
				__( 'Outside', 'startapp' ) => 'outside',
				__( 'Inside', 'startapp' )  => 'inside',
			),
		),
		array(
			'param_name'       => 'dots_alignment',
			'type'             => 'dropdown',
			'weight'           => 10,
			'heading'          => __( 'Dots Alignment', 'startapp' ),
			'group'            => __( 'Controls', 'startapp' ),
			'dependency'       => array( 'element' => 'is_dots', 'value' => 'show' ),
			'edit_field_class' => 'vc_col-sm-4',
			'std'              => 'center',
			'value'            => array(
				__( 'Left', 'startapp' )   => 'left',
				__( 'Center', 'startapp' ) => 'center',
				__( 'Right', 'startapp' )  => 'right',
			),
		),
		array(
			'param_name' => 'transition',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Transition Effect', 'startapp' ),
			'group'      => __( 'Behavior', 'startapp' ),
			'std'        => 'slide',
			'value'      => array(
				__( 'Slide', 'startapp' ) => 'slide',
				__( 'Fade', 'startapp' )  => 'fade',
			),
		),
		array(
			'param_name' => 'is_loop',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Loop', 'startapp' ),
			'group'      => __( 'Behavior', 'startapp' ),
			'std'        => 'disable',
			'value'      => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
		array(
			'param_name' => 'is_autoplay',
			'type'       => 'dropdown',
			'weight'     => 10,
			'heading'    => __( 'Autoplay', 'startapp' ),
			'group'      => __( 'Behavior', 'startapp' ),
			'std'        => 'disable',
			'value'      => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
		array(
			'param_name'  => 'autoplay_speed',
			'type'        => 'textfield',
			'weight'      => 10,
			'heading'     => __( 'Autoplay Speed', 'startapp' ),
			'description' => __( 'Any positive integer number', 'startapp' ),
			'group'       => __( 'Behavior', 'startapp' ),
			'dependency'  => array( 'element' => 'is_autoplay', 'value' => 'enable' ),
			'value'       => '3000',
		),
		array(
			'param_name'  => 'is_height',
			'type'        => 'dropdown',
			'weight'      => 10,
			'heading'     => __( 'Adaptive Height', 'startapp' ),
			'description' => __( 'Helpful for images with different height', 'startapp' ),
			'group'       => __( 'Behavior', 'startapp' ),
			'std'         => 'disable',
			'value'       => array(
				__( 'Enable', 'startapp' )  => 'enable',
				__( 'Disable', 'startapp' ) => 'disable',
			),
		),
	), 'startapp_image_carousel' ),
);
